version: '3.8'

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "9000" # FPM port
    environment:
      - MONGODB_URL=mongodb://mongo:27017/backend
      - MONGODB_DB=backend
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    ports:
      - "8000:80" # Expose nginx on localhost:8000
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    depends_on:
      - backend

  frontend:
    image: pp-frontend
    ports:
      - "3000:3000"
